/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Bell: typeof import('lucide-react')['Bell']
  const Button: typeof import('primereact/button')['Button']
  const CartesianGrid: typeof import('recharts')['CartesianGrid']
  const Checkbox: typeof import('primereact/checkbox')['Checkbox']
  const Column: typeof import('primereact/column')['Column']
  const DataTable: typeof import('primereact/datatable')['DataTable']
  const Dialog: typeof import('primereact/dialog')['Dialog']
  const Facebook: typeof import('lucide-react')['Facebook']
  const Globe: typeof import('lucide-react')['Globe']
  const InputText: typeof import('primereact/inputtext')['InputText']
  const Instagram: typeof import('lucide-react')['Instagram']
  const Legend: typeof import('recharts')['Legend']
  const Line: typeof import('recharts')['Line']
  const LineChart: typeof import('recharts')['LineChart']
  const Search: typeof import('lucide-react')['Search']
  const Settings: typeof import('lucide-react')['Settings']
  const Tooltip: typeof import('recharts')['Tooltip']
  const XAxis: typeof import('recharts')['XAxis']
  const YAxis: typeof import('recharts')['YAxis']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
